### ISSUE TITLE
autocomplete="one-time-code" and masked input

### ISSUE THREAD

**Issue by erizoy** [RobinHerbots/Inputmask#1985]
Hello
I'm using inputmask, and two-step auth in my project.
But when I'm try to use autocomplete="one-time-code" for automatically get codes from iMessage, safari can't paste code with masked input. On inputs without mask it works as expected.

Code:
`$("#smscode").inputmask({"mask" : "999999", showMaskOnHover: false});`

Safari 12.0 (14606.1.36.1.6)
MacOS Mojave beta 10.14 (18A371a)

**Comment by Dihlofos** [comment]
Same trouble(

**Comment by RobinHerbots** [comment]
Which version do you use. I guess this is fixed in thé current beta 5.x.
Can you have a try.

Op di 21 mei 2019 10:46 schreef Dihlofos <notifications@github.com>:

**Comment by Dihlofos** [comment]
I tried beta version ("inputmask": "^5.0.0-beta.158")
Not worked for me.

This is mask code:
Inputmask({
      "mask": "9999",
      clearMaskOnLostFocus: false,
      "oncomplete": function(){
        codeinput.blur()
      }
    }).mask(codeinput);

I use it on input with type="tel", maybe it is crucial. But changing to type="text" hasn't solve problem.

**Comment by Dihlofos** [comment]
So, I solved the propblem!
Atucomplete started to work when I added option "autoUnmask: true" to my mask init.
Thank you for support!

**Comment by RobinHerbots** [comment]
@Dihlofos , 

Can you reproduce this in a codepen or jsFiddle?  I would want to see why this option has impact on this when using a simple mask like 9999.

Best regards, 

Robin

**Comment by Dihlofos** [comment]
@RobinHerbots,

So I was wrong. And the problem was not in "autoUnmask: true" rule. I just tested it in wrong browser.
And as a result - autocomplete works fine in Iphone Chrome, but not works in Safari.
