### ISSUE TITLE
Unexpected behavior of remove option in preValidation 

### ISSUE THREAD

**Issue by ilplotkin** [RobinHerbots/Inputmask#2311]
```
<script src="jquery.js"></script>
<script src="jquery.inputmask-504.js"></script>

<input id="id1">

<script>

   var m = {
      mask: '(999)000',
      definitions: {
         '0': { validator: '[0-9]',  },
         '9': { validator: '[0-9- ]' }
      },
      preValidation: function (buffer, pos, c, isSelection, opts, maskset, caretPos) {
         if ( c === ' ' ) return {remove: pos};
         return true;
      },
   };

   var i = $('#id1');
   i.inputmask(m);
   i.inputmask('setvalue', '1  234'); // input contains '(1__)234' as expected
   i.inputmask('setvalue', '   234'); // input contains '(__2)34_', (___)234 expected

</script>

```

**Comment by RobinHerbots** [comment]
@ilplotkin , 

What do you want to accomplish in the preValidation?

**Comment by ilplotkin** [comment]
@RobinHerbots 

For compatibility reasons, we have to convert masks from another [format](https://documentation.devexpress.com/WindowsForms/1500/Controls-and-Libraries/Editors-and-Simple-Controls/Common-Editor-Features-and-Concepts/Input-Mask/Mask-Type-Simple) to Inputmask format. The problem is with leading optional groups (like phone number area code). I know the solution with alternate masks you recommend in #1884. But it is rather difficult to convert foreign arbitrary mask to the array of alternate masks in general case.
I am trying to resolve this problem in the following way. Introduce two definitions: with space for optional symbols and without space for mandatory ones. Before "setValue" invocation, analyze value and prepend/insert spaces according to mask. In preValidation, remove spaces to make it possible to enter symbols in those positions.

Thank you

**Comment by RobinHerbots** [comment]
@ilplotkin , 

I pushed a fix in 5.0.4-beta.37 which disable the skipoptionalprtchar (default is space) when setting the value.  This allows for correctly setting the   '   234' value.

The remove has not much use in your example.  As you remove the position and insert the space at the same position.

**Comment by ilplotkin** [comment]
@RobinHerbots 

Thank you very much.
Now I see `<space><space><space>234` (if I remove the line with `{remove: pos}`).
But I cannot enter anything over spaces until manually remove them using Del or Backspace. Actually this is the intention of `remove`: to make it possible to enter immediately. With `remove` I see underscores instead of spaces, can enter immediately but the issue still reproduced. IMHO the necessity to remove spaces manually is confusing.

**Comment by RobinHerbots** [comment]
@ilplotkin , 

something ike this ?

```
var m = {
			mask: '(999)000',
			definitions: {
				'0': {validator: '[0-9]'},
				'9': {validator: '[0-9- ]'}
			},
			preValidation: function (buffer, pos, c, isSelection, opts, maskset, caretPos) {
				if (maskset.validPositions[pos] && maskset.validPositions[pos].input === " ") return {remove: pos, rewritePosition: pos};
				return true;
			},
		};

```

**Comment by ilplotkin** [comment]
@RobinHerbots ,

Probably so...
Unfortunately, I do not quite understand how to finish your idea. Looks like that 'validPositions' is not ready at the moment and also closing parenthesis and one space are skipped.
```
      preValidation: function (buffer, pos, c, isSelection, opts, maskset, caretPos) {
         console.log(pos, maskset.validPositions[pos] && maskset.validPositions[pos].input);
         setTimeout(function(){console.log(pos, maskset.validPositions[pos] && maskset.validPositions[pos].input)});
         //if (maskset.validPositions[pos] && maskset.validPositions[pos].input === " ") return {remove: pos, rewritePosition: pos};
         return true;
      },

0 undefined
2 undefined
3 undefined
5 undefined
6 undefined
7 undefined
0 "("
2 " "
3 " " // parenthesis and space skipped
5 "2"
6 "3"
7 "4"

**Comment by RobinHerbots** [comment]
Doesn't the example work?

The validpositions only contain validated positions

**Comment by ilplotkin** [comment]
Unfortunately, it does not. `maskset.validPositions[pos]` is always `undefined`.

**Comment by RobinHerbots** [comment]
Go to https://codepen.io/robinherbots/pen/bGVqWZo

Set the caret into the position of the spaces and start typing 123

**Comment by ilplotkin** [comment]
I expected to see underscores instead of spaces. Misunderstanding. Sorry. Thank you very much.
I just replaced space with underscore in code and, seems, got expected result. I will investigate it.

**Comment by ilplotkin** [comment]
@RobinHerbots 

Thank you very much for your attention to our problem.

When I replace space with underscore I have seen underscores in "optional" positions and can enter digits over them immediately. Very well! Thank you. But I also would like to skip/clear "optional" positions on space key. I mean that, on space key pressed, underscore is appeared in current position, it is possible to enter in this position, caret moves to next position. I tried several variants but, unfortunately, without success. Is that possible? Can you help? Thank you

```
   var m = {
      mask: '(999)000',
      definitions: {
         '0': { validator: '[0-9]',  },
         '9': { validator: '[0-9_ ]' }
      },
      preValidation: function (buffer, pos, c, isSelection, opts, maskset, caretPos) {
         if ( maskset.validPositions[pos] && maskset.validPositions[pos].input === '_' ) return {remove: pos, rewritePosition: pos};
         return true;
      },
   };

   var i = $('#id1');
   i.inputmask(m);
   i.inputmask('setvalue', '___234');
```

**Comment by RobinHerbots** [comment]
@ilplotkin , 

I updated the codepen.

https://codepen.io/robinherbots/pen/bGVqWZo

**Comment by ilplotkin** [comment]
@RobinHerbots ,

Looks like "second idea" is that we are looking for.
Thank you very much.
Great work!
