### ISSUE TITLE
Can't delete digits after decimal point on negative numbers

### ISSUE THREAD

**Issue by jpontet** [RobinHerbots/Inputmask#892]
Hi,

Steps to reproduce:
- Create an input with a mask of decimal, and allowMinus: true
- Give the input a value of -34,873,289
- Then put a decimal before the 89, i.e. -34,873,2.89
- Delete using backspace from the current cursor position (which is to the right of the decimal)
- The result is .9 value remains which cannot be deleted with backspace or delete key

Note, see #870: we have implemented a fix that allows us to input a decimal before the 89. Currently, if you try to do this the code enters an infinite loop and the page freezes.

Thanks

**Comment by RobinHerbots** [comment]
@jpontet , 

Fixed

**Comment by jpontet** [comment]
Thanks @RobinHerbots I will check it out!

**Comment by jpontet** [comment]
@RobinHerbots can I asked what happened jquery.inputmask.js? Version 3.1.64-1 is 1361 lines but 3.1.64-48 is 58 lines...?

**Comment by RobinHerbots** [comment]
You can find it in the changelog.

The idea is to separate the core inputmask functionality from the plugin
code for jquery. Future version may also work without jquery or with other
frameworks.

Op do 21 mei 2015 om 15:15 schreef jpontet notifications@github.com:

**Comment by jpontet** [comment]
Thanks @RobinHerbots 
Ive updated to version 3.1.64-48 however I dont find the above scenario is fixed.
Granted you cant put a decimal between 2 existing numbers, you have to put it at the end of a number and then define the remainder, however I still find that when you backspace delete all numbers to the left of the decimal the remainder still exists and you cant delete it.

**Comment by RobinHerbots** [comment]
Hmm, can you create a jsfiddle to make it more clear.

Op do 21 mei 2015 om 17:13 schreef jpontet notifications@github.com:

**Comment by jpontet** [comment]
I hadnt updated the numeric extension as well. Its is working as expected. Thanks.
