### ISSUE TITLE
Cannot overwrite characters when highlighting the characters to the right of the decimal

### ISSUE THREAD

**Issue by shahvaiz** [RobinHerbots/Inputmask#974]
When I highlight the characters to the right of the decimal place, I cannot overwrite the characters. In the fiddle below, when highlighting "231", I cannot overwrite the value.

https://jsfiddle.net/1w19aadt/2/

**Comment by RobinHerbots** [comment]
Fixed

**Comment by shahvaiz** [comment]
The overwriting issue is fixed, but this release seems to have broken some other functionality. Please see the link below to my app: In Safari, I am no longer able to click into the "Interest Rate" field. The cursor seems to be locked in the "Loan Amount" field. In Chrome and FF, clicking on the "Interest Field Rate" field causes the cursor to jump to the left.

https://www.buckinghamfg.com/rates/?tab=1

**Comment by RobinHerbots** [comment]
Is this on osx? A quick test on win8 shows no problem.

**Comment by RobinHerbots** [comment]
Maybe related to #976

**Comment by shahvaiz** [comment]
I'm still having this issue on both Mac and Windows (Chrome, FF, and IE). On the link below, try clicking directly to the right of the '5' and the cursor will jump to the left. 

On Safari, the Interest Rate field is locked - I cannot click into it at all.

https://www.buckinghamfg.com/rates/?tab=1

**Comment by RobinHerbots** [comment]
@shahvaiz , 

The radixFocus option sets the caret just before the radixpoint on the first click inside.  Once the field has focus the caret stays on the clicked position.  Try disabling the radixFocus option.  I will have a look at safari tomorrow.

Hmm, ... maybe I can make the radixFocus a bit more intelligent to only set the caret to the radixpoint when it is desirable, ... no digits entered yet or something?

**Comment by shahvaiz** [comment]
Disabling radixFocus has the following effect:
1. No change in Safari or Chrome
2. On FF, the cursor does not jump to the left anymore. However, when clicking to the right of the '5' (in the value 4.125%), the cursor now jumps to the right of the percentage symbol.

The value in my form is pre-populated when the page loads. Typing a new value in the field does not change the behavior.

This issue is only occurring on decimal fields. Below is my code:

$('#id_interest_rate').inputmask("decimal", {
    "rightAlign": false,
    "placeholder": "",
    "digits": 3,
    "integerDigits": 2,
    "allowMinus": false,
    "autoUnmask": true,
    "suffix": '%'
  });

**Comment by RobinHerbots** [comment]
@shahvaiz, 

Have a look at the new version.

http://jsfiddle.net/pobo609e/

**Comment by shahvaiz** [comment]
This works perfectly in the JSfiddle. Hopefully it works on all of the browsers. Thanks.

**Comment by shahvaiz** [comment]
Working great on all browsers, including Safari. Thanks so much!
